---
- name: Sync MUNGE key from mgmt-1 to all nodes
  hosts: munge_group
  become: yes
  gather_facts: no

  vars:
    munge_key_path: /etc/munge/munge.key

  tasks:

    - name: Read MUNGE key from mgmt-1
      slurp:
        src: "{{ munge_key_path }}"
      register: munge_key_file
      delegate_to: management-1
      run_once: true

    - name: Deploy MUNGE key to all nodes
      copy:
        dest: "{{ munge_key_path }}"
        content: "{{ munge_key_file.content | b64decode }}"
        owner: munge
        group: munge
        mode: '0400'

    - name: Restart MUNGE on all nodes
      systemd:
        name: munge
        state: restarted
        enabled: yes
